name: Build and Test

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: Lint Codebase
        run: npm run lint
      - run: npx supabase start
      - run: npx supabase status --output=env > .env
      - run: echo "MODE=testing" >> .env
      - run: echo "CRON_SECRET=insecure_secret" >> .env
      - run: npm run build

      - name: Resolve Playwright Version
        id: playwright-version
        run: "echo \"playwright-version=$(npm list --long --json @playwright/test | jq -r .dependencies[\\\"@playwright/test\\\"].version)\" >> \"$GITHUB_OUTPUT\""

      - name: Cache Playwright
        id: playwright-cache
        uses: actions/cache@v5
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ steps.playwright-version.outputs.playwright-version }}
      - run: npx playwright install-deps
        if: steps.playwright-cache.outputs.cache-hit == 'true'
      - run: npx playwright install --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      - name: Cache Playwright Chrome
        id: playwright-cache-chrome
        uses: actions/cache@v5
        with:
          path: /opt/google/chrome
          key: playwright-chrome-${{ runner.os }}-${{ steps.playwright-version.outputs.playwright-version }}
      - run: npx playwright install-deps chrome
        if: steps.playwright-cache-chrome.outputs.cache-hit == 'true'
      - run: npx playwright install chrome
        if: steps.playwright-cache-chrome.outputs.cache-hit != 'true'

      - name: Cache Playwright Edge
        id: playwright-cache-edge
        uses: actions/cache@v5
        with:
          path: /opt/microsoft/msedge
          key: playwright-edge-${{ runner.os }}-${{ steps.playwright-version.outputs.playwright-version }}
      - run: npx playwright install-deps msedge
        if: steps.playwright-cache-edge.outputs.cache-hit == 'true'
      - run: npx playwright install msedge
        if: steps.playwright-cache-edge.outputs.cache-hit != 'true'

      - run: npm test
      - name: Archive code coverage results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            playwright-report
            test-results
